//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopServiceLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class CatalogItemsStock
    {
        [DataMember]
        public System.DateTime Date { get; set; }
        [DataMember]
        public int CatalogItemId { get; set; }
        [DataMember]
        public int AvailableStock { get; set; }
        [DataMember]
        public int StockId { get; set; }
    }
}
