//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogItem
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public byte[] Picture { get; set; }
        public int CatalogBrandId { get; set; }
        public int CatalogTypeId { get; set; }
    }
}
